platform:
  - x64

clone_folder: c:\gopath\src\github.com\la5nta\wl2k-go

environment:
  global:
    GOPATH: C:\gopath
    GOVERSION: "1.16.5"
    MSYS_PATH: C:\MinGW\msys\1.0
install:
  - set PATH=C:\go\bin;%MSYS_PATH%\bin;C:\MinGW\bin;%PATH%
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://dl.google.com/go/go%GOVERSION%.windows-386.zip
  - 7z x go%GOVERSION%.windows-386.zip -y -oC:\ > NUL
build_script:
  - go version
  - go test -v ./...
