// Code generated by "stringer -type=State ."; DO NOT EDIT.

package ardop2

import "strconv"

const _State_name = "UnknownOfflineDisconnectedISSIRSQuietFECSendFECReceive"

var _State_index = [...]uint8{0, 7, 14, 26, 29, 32, 37, 44, 54}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
